Пробный первый...
vladibon/wallet pull request #2
Opened 2022-04-02 18:44 UTC by vitaly171

2022-04-02 20:52 UTC, vladibon requested changes

2022-04-02 20:52 UTC, vladibon commented on src/components/LoginForm/LoginForm.module.css
> +    }
У контейнера должна быть max-width по точкам перелома. Иначе контент не фиксируется по центру.

2022-04-02 20:52 UTC, vladibon commented on src/components/LoginForm/LoginForm.jsx
> +            <svg className={s.logoIcon}>
Логотип нужно вынести в отдельный файл или создать спрайт.
`<svg>
       <use href=""></use>
  </svg>`

2022-04-02 20:52 UTC, vladibon commented on src/components/LoginForm/LoginForm.module.css
> +        background-position: top -15px right -15px;
background-position: top -15px right -15px; 
это свойство обрезает картинку сверху и справа. 
Может лучше использовать:  top: ; right: ; ?
тогда и маржины не нужны будут....

2022-04-02 21:12 UTC, Olena-Horobets requested changes

2022-04-02 21:12 UTC, Olena-Horobets commented on src/components/LoginForm/LoginForm.jsx
> +            <svg className={s.logoIcon}>
вместе с остальными иконками. Также можно создать компонент лого и переиспользовать его

2022-04-02 21:12 UTC, Olena-Horobets commented on src/components/LoginForm/LoginForm.module.css
> +.inputIcon :hover{
ховер иконки лучше перенести на label. тогда пользователь увидит ховер уже на всём инпуте

2022-04-02 21:12 UTC, Olena-Horobets commented on src/components/LoginForm/LoginForm.jsx
> +    <div className={s.container}>
это всё должно быть в компоненте LoginPage. здесь только форма

2022-04-04 19:51 UTC, vladibon requested changes

2022-04-04 19:51 UTC, vladibon commented on src/components/LoginForm/LoginForm.module.css
> +  border-bottom: 0.5px, solid;
Нужно убрать запятую. Иначе свойство не применяется.
border-bottom: 0.5px solid;

2022-04-04 22:28 UTC, merged